{% set name = "pyserial-asyncio" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyserial-asyncio-{{ version }}.tar.gz
  sha256: b6032923e05e9d75ec17a5af9a98429c46d2839adfaf80604d52e0faacd7a32f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pyserial
    - python >={{ python_min }}

test:
  imports:
    - serial_asyncio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyserial/pyserial-asyncio
  summary: Python Serial Port Extension - Asynchronous I/O support
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: |
    Async I/O extension package for the Python Serial Port Extension for OSX, Linux, BSD
  doc_url: https://pyserial-asyncio.readthedocs.io
  dev_url: https://github.com/pyserial/pyserial-asyncio

extra:
  recipe-maintainers:
    - beenje
